image: gitlab.praktikum-services.ru:5050/std-016-018/sausage-store/sausage-frontend:latest
replicas: 2
imagePullPolicy: IfNotPresent
revisionHistoryLimit: 15
ImagePullSecret:
  name: docker-config-secret
service:
  port: 8080
fqdn: "std-016-018.k8s.praktikum-services.tech"
