---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  spring_datasource_url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi16cGw0a202bnkyaW1iMnhmLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDE2LTAxOA==
  spring_datasource_username: c3RkLTAxNi0wMTg=
  spring_datasource_password: VGVzdHVzcjEyMzQ= 
  spring_data_mongodb_uri: bW9uZ29kYjovL3N0ZC0wMTYtMDE4OlRlc3R1c3IxMjM0QHJjMWEtNWlmNDBjZWYzNHZzbXV0OS5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3N0ZC0wMTYtMDE4P3JlcGxpY2FTZXQ9cnMwMSZ0bHM9dHJ1ZQ==
#  vault_token: aHZzLm1zZldyZURZczVybVFIRWJBRHlzQnIxNQ==
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoia3ViX3lkdWFldiIsCiAgICAgICAgICAgICJwYXNzd29yZCI6InlGelZ4SFBjWkJtejhBUUFDdGhwIgogICAgICAgIH0KICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
