---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: backend
  updatePolicy:
    updateMode: "{{ .Values.updateMode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["{{ .Values.controlledResources.value1 }}", "{{ .Values.controlledResources.value2 }}"]
        controlledValues: RequestsAndLimits
