---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  revisionHistoryLimit: 15
  replicas: 1
  selector:
    matchLabels:
      app: backend-report
  serviceName: "backend-report"
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/std-016-018/sausage-store/sausage-backend-report:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: spring_data_mongodb_uri 
      imagePullSecrets:
        - name: docker-config-secret
